#!/bin/sh

PIPEFILE="$1"
PIPEDIR="$(dirname $PIPEFILE)"

while [ -p "$PIPEFILE" ]; do
	INPUT="$(cat "$PIPEFILE")"
	while [ -n "$INPUT" ]; do
		CMDLINE="$(echo "$INPUT" | head -n 1)"
		INPUT="$(echo "$INPUT" | tail -n +2)"
		CMDUID=$(echo $CMDLINE | cut -f1 -d:)
		CMDCWD=$(echo $CMDLINE | cut -f2 -d:)
		INPIPE=$(echo $CMDLINE | cut -f3 -d:)
		CALLERTTY=$(echo $CMDLINE | cut -f4 -d:)
		CMD=$(echo $CMDLINE | cut -f5- -d:)
		CMDUSERNAME=$(id -un $CMDUID)
		ENVFILE="$PIPEDIR/env.$CMDUSERNAME"

		# echo $CMDLINE
		# echo "netns-user CMDLINE     $CMDLINE" >> /home/tinou/netns.log
		# echo "netns-user CMDUID      $CMDUID" >> /home/tinou/netns.log
		# echo "netns-user CMDCWD      $CMDCWD" >> /home/tinou/netns.log
		# echo "netns-user INPIPE      $INPIPE" >> /home/tinou/netns.log
		# echo "netns-user CALLERTTY   $CALLERTTY" >> /home/tinou/netns.log
		# echo "netns-user CMD         $CMD" >> /home/tinou/netns.log
		# echo "netns-user CMDUSERNAME $CMDUSERNAME" >> /home/tinou/netns.log
		# echo "netns-user ENVFILE     $ENVFILE" >> /home/tinou/netns.log

		if [ "$CALLERTTY" = "KILLME" ]; then
			kill $(cat "${INPIPE}.pid")
		elif [ -n "$CMD" ]; then
cat <<EOF | zsh >/dev/null
$(readenv $ENVFILE)
cd '$CMDCWD'
if [ -c "$CALLERTTY" ] && [ -e "$INPIPE" ]; then
    cat '$INPIPE' | script -qaf '$CALLERTTY' -c '$CMD ; rm -f $INPIPE ${INPIPE}.pid' &
else
	exec 3> $CALLERTTY
	( \$SHELL -c '$CMD' >$CALLERTTY 2>$CALLERTTY ; exec 3>&- ; rm -f $INPIPE ${INPIPE}.pid $CALLERTTY ) &
fi
echo \$! > ${INPIPE}.pid
exit 0
EOF
		fi
	done
done
echo "netns-user ($CMDUSERNAME) exiting"
