#!/bin/zsh

$(readconf /etc/netns.conf)

PIPEFILE=$NETNSDIR/cmdpipe
PIDFILE=$(dirname $PIPEFILE).pid

COMMAND=$1

if [ "$COMMAND" = "start" ]; then
	echo "Starting netns command pipe."
	mkdir -p $(dirname $PIPEFILE)/pipes
	chgrp netns $(dirname $PIPEFILE){,/pipes}
	chmod g+w $(dirname $PIPEFILE){,/pipes}
	if ! [ -p $PIPEFILE ]; then
		mkfifo $PIPEFILE
	fi
	chgrp netns $PIPEFILE
	chmod 660 $PIPEFILE
	echo $$ > "$PIDFILE"

	while [ -e "$PIDFILE" ]; do
		/usr/lib/netns-cmdpipe-listen "$PIPEFILE"
		echo "Restarting netns-cmdpipe"
		ps u | wc -l
	done
elif [ "$COMMAND" = "stop" ]; then
	if [ -e "$PIDFILE" ]; then
		echo "Stopping netns command pipe."
		if [ -e "$PIPEFILE" ]; then
			rm $PIPEFILE ${PIPEFILE}.[0-9]*
		fi
		wait $(cat $PIDFILE)
		rm -f $PIDFILE
	else
		echo "netns command pipe not started."
	fi
elif [ "$COMMAND" = "restart" ]; then
	$0 stop
	$0 start
fi
